language: erlang
sudo: false

install:
   - wget -c https://github.com/erlang/rebar3/releases/download/3.7.5/rebar3 && chmod +x rebar3 && ./rebar3 update

otp_release:
    - 21.1
    - 20.3
    - 19.3
    - 18.3

script: ./rebar3 do compile, ct
